"""initial_research_workspace

Revision ID: d42026f707b5
Revises: 
Create Date: 2026-09-18 23:37:06.048299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd42026f707b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_device_owner_id'), 'device', ['owner_id'], unique=False)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status_note', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('next_step', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_owner_id'), 'project', ['owner_id'], unique=False)
    op.create_table('workingcopy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('head', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('upstream', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('remote_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('changed_files', sa.Integer(), nullable=False),
    sa.Column('untracked_files', sa.Integer(), nullable=False),
    sa.Column('ahead', sa.Integer(), nullable=True),
    sa.Column('behind', sa.Integer(), nullable=True),
    sa.Column('comparison', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'local_path', name='uq_device_path')
    )
    op.create_index(op.f('ix_workingcopy_device_id'), 'workingcopy', ['device_id'], unique=False)
    op.create_index(op.f('ix_workingcopy_project_id'), 'workingcopy', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workingcopy_project_id'), table_name='workingcopy')
    op.drop_index(op.f('ix_workingcopy_device_id'), table_name='workingcopy')
    op.drop_table('workingcopy')
    op.drop_index(op.f('ix_project_owner_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('item')
    op.drop_index(op.f('ix_device_owner_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
